# Generated by Django 3.0.2 on 2020-01-08 22:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('letter', models.TextField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=50, verbose_name='Имя')),
                ('content', models.TextField(max_length=15000, verbose_name='Содержимое')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата')),
                ('title', models.TextField(max_length=150, verbose_name='Название треда')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=50, verbose_name='Имя')),
                ('content', models.TextField(max_length=15000, verbose_name='Содержимое')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата')),
                ('sage', models.BooleanField(default=False, verbose_name='SAGE')),
                ('op_mark', models.BooleanField(default=False, verbose_name='ОП треда')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Post.thread+', to='imageboard.Thread', verbose_name='Тред')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='FileThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'mp4', 'webm'])], verbose_name='Файлы')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Thread')),
            ],
            options={
                'verbose_name': 'Файл треда',
                'verbose_name_plural': 'Файлы тредов',
            },
        ),
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'mp4', 'webm'])], verbose_name='Файлы')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Post')),
            ],
            options={
                'verbose_name': 'Файл поста',
                'verbose_name_plural': 'Файлы постов',
            },
        ),
    ]
